# Generated by Django 4.2.7 on 2023-12-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='mainapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_add', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.product')),
            ],
        ),
    ]
