# Generated by Django 4.2.7 on 2023-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_order_total_price_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadd',
            name='quantity_add',
            field=models.PositiveIntegerField(),
        ),
    ]
